[package]
name = "rustvoxels"
version = "0.1.0"
authors = ["Id405 <8o7wermobile@gmail.com>"]
edition = "2018"
resolver="2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = { version = "1.7", features = [ "derive" ] }
cgmath = "0.18.0"
env_logger = "0.8.4"
futures = "0.3.15"
shaderc = "0.7.2"
wgpu = "0.10"
winit = "0.25.0"
